Environment Drivers Refactor + Documentation
traitecoevo/plant pull request #340
Opened 2022-06-18 14:13 UTC by devmitch

Since #334 abstracted `ExtrinsicDrivers` into its own class, we can now clean up the old driver API in `Environment` and replace all the methods with an exposed `ExtrinsicDrivers` object. #334 also included a smarter way to set up drivers, which is also included in this PR:
Default (rainfall = 1):
```r
env <- make_environment("FF16w")
```
Constant:
```r
env <- make_environment("FF16w", rainfall=3.14)
```
Variable:
```r
x_pts <- seq(0, 200, 1)
rain <- list(
  x = x_pts,
  y = 1 + sin(x_pts)
)
env <- make_environment("FF16w", rainfall=rain)
```
Evaluation is now done like this:
```r
env$extrinsic_drivers$evaluate("rainfall", 5.634)
env$extrinsic_drivers$evaluate_range("rainfall", c(5, 1.2, 78.345))
```

These examples have also been included in a new vignette at `vignettes/extrinsic_drivers.Rmd`. It is only a draft as of now. I can't seem to knit R code or embed images (other vignettes use a `figure/` directory, which I can't seem to find...). I would appreciate your input on the documentation!

2022-06-26 22:52 UTC, aornugent approved these changes

2022-06-26 22:53 UTC, aornugent commented
This looks great @devmitch! I forget exactly the workflow for rebuilding the website, but can knit your vignette successfully.

2022-08-01 22:22 UTC, dfalster commented
Hi @devmitch 

Vignette is very good! I just added some minor changes. You can test rendering using 

```
rmarkdown::render("vignettes//strategy_FF16.Rmd")
```

I've used another vignette above, as currently this branch isn't compiling. E.g. see 

https://github.com/traitecoevo/plant/runs/7160778238?check_suite_focus=true

Can you follow up on the compilation?

2022-08-01 22:23 UTC, dfalster commented
I'll post a separate issue about updating the vignettes in general. Bunch are out of date.

2022-08-01 23:05 UTC, dfalster commented
Also, @devmitch 

How does this branch relate to https://github.com/traitecoevo/plant/tree/doc-updates?

2022-08-01 23:05 UTC, dfalster requested changes
Looking very good. 

However, this branch is currently not compiling for me, or passing GH actions.

2022-08-10 11:40 UTC, devmitch commented
> Also, @devmitch
> 
> How does this branch relate to https://github.com/traitecoevo/plant/tree/doc-updates?

Pretty sure that branch contains an outdated and incomplete version of the vignette I have pushed on this branch.

> Looking very good.
> 
> However, this branch is currently not compiling for me, or passing GH actions.

Hopefully everything should be compiling now, I'm going to attempt the get_state changes on another branch/PR just to separate concerns.

2022-08-11 03:20 UTC, dfalster approved these changes
Nice work @devmitch

2022-08-11 03:21 UTC, dfalster commented
Feel free to merge

2022-08-11 09:34 UTC, aornugent commented on vignettes/extrinsic_drivers.Rmd
> +ctrl <- Control()
Maybe try `scm_base_control` here.

2022-08-11 10:53 UTC, merged